---
kind: Service
apiVersion: v1
metadata:
  name: nodeservices
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8081
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: metallurgical/nodeexample:v0.0.1
          ports:
            - containerPort: 8081
